version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --user=root
    ports:
      - "3307:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "university"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: '%'
    networks:
      - spring-microservices
networks:
  spring-microservices: