version: "3.8"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --user=root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "university"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: '%'
    networks:
      - spring-microservices
  eureka-server:
    image: bindian0509/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-microservices
    depends_on:
      - mysql
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring-microservices
    depends_on:
      - eureka-server
  api-gateway:
    image: bindian0509/api-gateway:latest
    container_name: api-gateway
    ports:
      - "9090:9090"
    networks:
      - spring-microservices
    depends_on:
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE : "http://eureka-server:8761/eureka"
      SPRING_ZIPKIN_BASE-URL : "http://zipkin:9411"
  config-server:
    image: bindian0509/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - spring-microservices
    depends_on:
      - api-gateway
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE : "http://eureka-server:8761/eureka"
  address-service:
    image: bindian0509/address-service:latest
    container_name: address-service
    ports:
      - "8081:8081"
    networks:
      - spring-microservices
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE : "http://eureka-server:8761/eureka"
      SPRING_ZIPKIN_BASE-URL : "http://zipkin:9411"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/university"
      SPRING_DATASOURCE_PASSWORD: "root"
  student-service:
    image: bindian0509/student-service:latest
    container_name: student-service
    ports:
      - "8080:8080"
    networks:
      - spring-microservices
    depends_on:
      - address-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE : "http://eureka-server:8761/eureka"
      SPRING_ZIPKIN_BASE-URL : "http://zipkin:9411"
      SPRING_DATASOURCE_URL : "jdbc:mysql://mysql:3306/university"
      SPRING_DATASOURCE_PASSWORD : "root"
networks:
  spring-microservices: