apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-services-configmap
data:
  SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
  EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: "http://eureka-server:8761/eureka"
